# Basic settings
from_latest_tag = true
ignore_merge_commits = true

# Changelog settings
[changelog]
path = "CHANGELOG.md"
#template = "remote"
remote = "github.com"
owner = "FabriceT"
repository = "test-go"
