# Basic settings
from_latest_tag = false
ignore_merge_commits = true
tag_prefix = "v"

# Changelog settings
[changelog]
path = "CHANGELOG.md"
#template = "remote"
remote = "github.com"
owner = "FabriceT"
repository = "test-go"
